### ISSUE TITLE
All department are loaded in the same region (Alsace)

### ISSUE THREAD

**Issue by gelhaimer** [Lyssal/geographie-bundle#2]
When executing the import command, all departments are linked to the first region of the list (Alsace).

This is due to an error in the of `getRegionFranceByDepartement()`.
Two variables were named the same ($departementCode).

Once corrected, there were missing department-region association. I took benefit of this fix to update region's liste with the new one from 2016.

**Comment by Lyssal** [comment]
Oups. Thank you very much for this correction !
